name: Test runner 

on: [push]

jobs:
  build:

    runs-on: [self-hosted, oracle]
    steps:
    - uses: actions/checkout@v2

    - name: Get Hostname
      run: |
        hostname
    - name: Get system Information
      run: |
        uname -a
    - name: Get Architecture
      run: |
        dpkg --print-architecture
