name: Test runner 

on: [push]

jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Get Hostname
      run: |
        hostname
    - name: Get system Information
      run: |
        systeminfo
    - name: Get Architecture
      run: |
        SET Processor
